Learn to handle missing values
Learn to fit a decision tree and compare its accuracy with random forest classifier.

In [25]:
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline 
from sklearn import metrics 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier
#from sklearn.preprocessing import Imputer 
import numpy as np 
from sklearn.impute import SimpleImputer
import numpy as np
Imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [12]:
df_horse=pd.read_csv("horse.csv")

In [13]:
df_horse.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   surgery                299 non-null    object
 1   age                    299 non-null    object
 2   hospital_number        299 non-null    int64
 3   rectal_temp            239 non-null    float64
 4   pulse                  275 non-null    float64
 5   respiratory_rate       241 non-null    float64
 6   temp_of_extremities    243 non-null    object
 7   peripheral_pulse       230 non-null    object
 8   mucous_membrane        252 non-null    object
 9   capillary_refill_time  267 non-null    object
 10  pain                   244 non-null    object
 11  peristalsis            255 non-null    object
 12  abdominal_distention   243 non-null    object
 13  nasogastric_tube       195 non-null    object
 14  nasogastric_reflux     193 non-null    object
 15  nasogastric_reflux_ph  53 non-null     float64
 16  rectal_exam_feces      197 non-null    object
 17  abdomen                181 non-null    object
 18  packed_cell_volume     270 non-null    float64
 19  total_protein          266 non-null    float64
 20  abdomo_appearance      134 non-null    object
 21  abdomo_protein         101 non-null    float64
 22  outcome                299 non-null    object
 23  surgical_lesion        299 non-null    object
 24  lesion_1               299 non-null    int64
 25  lesion_2               299 non-null    int64
 26  lesion_3               299 non-null    int64
 27  cp_data                299 non-null    object
dtypes: float64(7), int64(4), object(17)
memory usage: 65.5+ KB

In [14]:
df_horse.head()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,NaN,more_3_sec,...,45.0,8.4,NaN,NaN,died,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,NaN,NaN,lived,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,...,74.0,7.4,NaN,NaN,died,no,4300,0,0,no

In [ ]:
# 1.Letâ€™s attempt to predict the survival of a horse based on various observed medical conditions.
# Load the data from â€˜horses.csvâ€™ and observe whether it contains missing values.
# [Hint: Pandas dataframe has a method isnull]

In [16]:
df_horse.isna()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,False,False,False,False,False,False,False,False,True,False,...,False,False,True,True,False,False,False,False,False,False
1,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False,False,...,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,False,False,False,True,False,False,False,True,False,False,...,False,False,True,True,False,False,False,False,False,False
295,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
296,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False

In [17]:
Y = df_horse["outcome"]
X= df_horse.drop(["outcome"],axis=1)

In [ ]:
# 2.This dataset contains many categorical features, replace them with label encoding.
# [Hint: Refer to get_dummies methods in pandas dataframe or Label encoder in scikit-learn]

In [33]:
X = pd.get_dummies(X)

In [34]:
X.head()

,hospital_number,rectal_temp,pulse,respiratory_rate,nasogastric_reflux_ph,packed_cell_volume,total_protein,abdomo_protein,lesion_1,lesion_2,...,abdomen_firm,abdomen_normal,abdomen_other,abdomo_appearance_clear,abdomo_appearance_cloudy,abdomo_appearance_serosanguious,surgical_lesion_no,surgical_lesion_yes,cp_data_no,cp_data_yes
0,530101,38.5,66.0,28.0,2.0,45.0,8.4,2.0,11300,0,...,0,0,0,0,0,0,1,0,1,0
1,534817,39.2,88.0,20.0,2.0,50.0,85.0,2.0,2208,0,...,0,0,1,0,1,0,1,0,1,0
2,530334,38.3,40.0,24.0,2.0,33.0,6.7,2.0,0,0,...,0,1,0,0,0,0,1,0,0,1
3,5290409,39.1,164.0,84.0,5.0,48.0,7.2,5.3,2208,0,...,0,0,0,0,0,1,0,1,0,1
4,530255,37.3,104.0,35.0,2.0,74.0,7.4,2.0,4300,0,...,0,0,0,0,0,0,1,0,1,0

In [ ]:
# 3.Replace the missing values by the most frequent value in each column.
# [Hint: Refer to Imputer class in Scikit learn preprocessing module]

In [29]:
#from sklearn.preprocessing import Imputer 
#imp = Imputer(missing_values='NaN', strategy='mean',axis=0)
#imp=imp.fit(df_horse.iloc[:,1:])
#df_horse.iloc[:,1:]=imp.transfrom(df_horse.iloc[:,1:])

In [35]:
X=X.apply(lambda x: x.fillna(x.value_counts().index[0]))

In [ ]:
# 4.Fit a decision tree classifier and observe the accuracy.

In [36]:
dec_tree=DecisionTreeClassifier()
dec_tree.fit(X,Y)
predicted_outcome=dec_tree.predict(X)
metrics.accuracy_score(predicted_outcome,Y)

1.0

In [ ]:
# 5.Fit a random forest classifier and observe the accuracy

In [37]:
random_forest=RandomForestClassifier()
random_forest.fit(X,Y)
predicted_outcome=random_forest.predict(X)
metrics.accuracy_score(predicted_outcome,Y)

1.0